influxdb:
  image: influxdb:1.8.4
  container_name: influxdb
  ports:
    - 8086:8086
  volumes:
    - /tmp/exchange/influxdb:/var/lib/influxdb
  environment:
      INFLUXDB_DB: influxdb_exchange
  restart:
    always

grafana:
  image: grafana/grafana:7.4.0
  container_name: grafana
  ports:
    - 3001:3000
  volumes:
    - /tmp/exchange/grafana:/var/lib/grafana
    - ./grafana/provisioning:/etc/grafana/provisioning
    - ./grafana/dashboards:/etc/grafana/dashboards
  restart:
    always
  environment:
    - GF_INSTALL_PLUGINS=https://github.com/ilgizar/ilgizar-candlestick-panel/raw/master/pack/ilgizar-candlestick-panel.zip;ilgizar-candlestick-panel