apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://host.docker.internal:8086
  password:
  user:
  database: influxdb_exchange
  basicAuth: false
  basicAuthUser:
  basicAuthPassword:
  withCredentials:
  isDefault: true
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
  secureJsonData:
    tlsCACert: ""
    tlsClientCert: ""
    tlsClientKey: ""
  version: 1
  editable: true