apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://host.docker.internal:8086
  database: influxdb_exchange
  isDefault: true
  jsonData:
    version: Flux
    organization: "myorg"
    defaultBucket: exchange
    tlsSkipVerify: true
    timeInterval: "1m"
  secureJsonData:
    token: "my-super-secret-auth-token"
  editable: true