name: InfluxDB logging

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: |
        mkdir -p /tmp/exchange/influxdb
        mkdir -p /tmp/exchange/grafana
        cd setup/influxdb/
        docker-compose up -d
    - name: Sleep
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'
    - name: Check running containers
      run: docker ps -a
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f setup/influxdb/requirements.txt ]; then pip install -r setup/influxdb/requirements.txt; fi
    - name: Test with unittest
      run: |
        python -m unittest discover async_exchange/logging/tests/
